name: Calendar update

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
  - cron: "0 0 * * *" # At the end of every day

  workflow_dispatch:  # workflow_dispatch = can be triggered manually
    # Inputs the workflow accepts.
    inputs:
      YEAR_REQUEST:
        description: 'Requested year'
        default: '2023'
        required: true
      MONTH_REQUEST:
        description: 'Used month, 0 for all year'
        default: '2'
        required: true
        type: choice
        options:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
      USER_REQUEST:
        description: 'User to update'
        default: 'Aurore'
        required: true
        type: choice
        options:
        - Axel
        - Aurélie
        - Aurore

jobs:
  runner:

    runs-on: ubuntu-latest

    env: # Or as an environment variable
      CI_PROJECT_ID: ${{ secrets.CI_PROJECT_ID }}
      CI_PRIVATE_KEY_ID: ${{ secrets.CI_PRIVATE_KEY_ID }}
      CI_PRIVATE_KEY: ${{ secrets.CI_PRIVATE_KEY }}
      CI_CLIENT_EMAIL: ${{ secrets.CI_CLIENT_EMAIL }}
      CI_CLIENT_ID: ${{ secrets.CI_CLIENT_ID }}
      CI_CLIENT_X509_CERT_URL: ${{ secrets.CI_CLIENT_X509_CERT_URL }}
      LAST_UPDATE: ${{ vars.LAST_UPDATE }}

    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script
        run: |
          set -xe
          python app.py ${{ github.event.inputs.YEAR_REQUEST }} \
          ${{ github.event.inputs.MONTH_REQUEST }} \
          ${{ github.event.inputs.USER_REQUEST }}
          echo test
          echo "LAST_UPDATE=yellow" >> "$GITHUB_ENV"
          echo $LAST_UPDATE

      - name: test env
        run: |
          echo ${{ LAST_UPDATE }}
      
