name: run main.py

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      YEAR_REQUEST:
        # Friendly description to be shown in the UI instead of 'YEAR_REQUEST'
        description: 'year'
        # Default value if no value is explicitly provided
        default: '2023'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run app.py
        env:
          SECRET_TEST: ${{ secrets.SECRET_TEST }}
        run: python app.py
