name: Unit Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write
      # Gives the action the necessary permissions for looking up the
      # workflow that launched this workflow, and download the related
      # artifact that contains the comment to be published
      actions: read
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install coverage
          pip install -r requirements.txt
          
      - name: execute py unit test
        env:
          CI_PROJECT_ID: ${{ secrets.CI_PROJECT_ID }}
          CI_PRIVATE_KEY_ID: ${{ secrets.CI_PRIVATE_KEY_ID }}
          CI_PRIVATE_KEY: ${{ secrets.CI_PRIVATE_KEY }}
          CI_CLIENT_EMAIL: ${{ secrets.CI_CLIENT_EMAIL }}
          CI_CLIENT_ID: ${{ secrets.CI_CLIENT_ID }}
          CI_CLIENT_X509_CERT_URL: ${{ secrets.CI_CLIENT_X509_CERT_URL }}
        run: coverage run -m unittest discover

      - name: unit test report
        run: coverage report && coverage html

      - name: Coverage comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}